### ISSUE TITLE
Testing OnlineSession example

### ISSUE THREAD

**Issue by lolriley** [HeatXD/GekkoNet#23]
Hello,

Is there a reason when I try to run the online session test. It just crashes with 
libc++abi: terminating due to uncaught exception of type std::invalid_argument: Invalid endpoint string

I tried it with  ./example 1 8000 127.0.0.1
And I wanted to have another local test client running on port 8001.

**Comment by HeatXD** [comment]
oh sorry i didnt add proper docs

OnlineSession.exe 0 1111 127.0.0.1:2222

it should be formatted like that

OnlineSession <localplayer> <localport> <remoteip:port>
